#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/app"

chmod -R 750 "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

mkdir -p "$install_dir/app/data/_data_/_default_/configs"
ynh_config_add --template="application.ini" --destination="$install_dir/app/data/_data_/_default_/configs/application.ini"

chown -R $app:$app "$install_dir/app/data"
chmod -R 600 "$install_dir/app/data"

#=================================================
# SETUP SSO
#=================================================
ynh_script_progression "Applying SSO patch..."

ynh_config_add --template="sso.php" --destination="$install_dir/index.php"
chown "$app:www-data" "$install_dir/index.php"
chmod 750 "$install_dir/index.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
