#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
